trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  jobs:
  - deployment: DeployWithHelm
    displayName: Deploy Robot Shop with Helm
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersionToInstall: 'latest'

          - task: HelmDeploy@0
            displayName: Helm Upgrade Install
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'robotshop-aks-connection'
              namespace: 'default'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'K8s/helm'
              releaseName: 'robot-shop'
              install: true
